# Generated by Django 5.1 on 2024-08-27 13:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_remove_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='anios_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consulta_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario_atencion',
            field=models.CharField(default='08:00-17:00', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_actual',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(default='1234567', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pacientes_asignados',
            field=models.ManyToManyField(related_name='doctores_asignados', to='historial.paciente'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='telefono_contacto',
            field=models.CharField(default='3214567890', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(default='No se ha registrado historial médico.'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
