# Generated by Django 5.1 on 2024-08-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_remove_paciente_birth_date_doctor_anios_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='telefono',
        ),
    ]
