# Generated by Django 5.1 on 2024-08-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0005_remove_doctor_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(default=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
