# Generated by Django 5.1 on 2024-08-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0006_remove_doctor_user_paciente_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
    ]
