# Generated by Django 5.1 on 2024-08-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0007_remove_paciente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
