# Generated by Django 5.1 on 2024-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0009_remove_paciente_user_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dataComplete',
            field=models.BooleanField(default=False),
        ),
    ]
